mybatis-plus:
  global-config:
    db-config:
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
  mapper-locations: classpath:/mappers/*.xml

mybatis:
  configuration:
    jdbc-type-for-null: null

ribbon:
  ReadTimeout: 30000    # 远程调用读取超时
  ConnectTimeout: 5000  # 远程调用连接超时

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr:}
        namespace: ${spring.cloud.nacos.config.namespace:}
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx:xxxx/xxx?serverTimezone=UTC&autoReconnect=true&useSSL=false&useOldAliasMetadataBehavior=true
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  redis:
    database: 1
    host: xx.xx.xx.xx
    port: 6379
    password: xxxx
    sentinel:
      master: mymaster
      nodes:
        - xx.xx.xx.xx:26379
        - xx.xx.xx.xx:26379
  xxl-job:
    adminAddresses: http://xx.xx.xx.xx/xxl-job-admin
    port: 8051
    log-path: ../logs/

logging:
  path: /xx/xx/xx/
  level:
    com.tft: debug
    com.alibaba.nacos.client.naming: error
  file:
    max-size: 500MB
    max-history: 200
  pattern:
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'
